package com.example.demo;

import com.example.demo.exception.BadRequestException;
import com.example.demo.exception.ResourceNotFoundException;
import com.example.demo.model.*;
import com.example.demo.repository.*;
import com.example.demo.security.CustomUserDetailsService;
import com.example.demo.security.JwtTokenProvider;
import com.example.demo.service.impl.*;
import org.mockito.Mockito;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import java.lang.reflect.Field;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.when;

/**
 * 60+ TestNG tests in required topic order:
 *  1. Simple servlet / Tomcat (Spring Boot controller-level tests)
 *  2. CRUD operations (services/repositories)
 *  3. DI and IoC (service wiring tests)
 *  4. Hibernate configurations & CRUD (entity + repository behaviour)
 *  5. JPA mapping & normalization
 *  6. Many-to-Many & associations (simulated via relationships)
 *  7. Security & JWT auth
 *  8. HQL / HCQL style queries via Spring Data
 */
@Listeners(TestResultListener.class)
public class BinOverflowPredictorTestNGTests {

    private BinRepository binRepository;
    private FillLevelRecordRepository recordRepository;
    private UsagePatternModelRepository modelRepository;
    private OverflowPredictionRepository predictionRepository;
    private ZoneRepository zoneRepository;

    private BinServiceImpl binService;
    private FillLevelRecordServiceImpl recordService;
    private UsagePatternModelServiceImpl modelService;
    private OverflowPredictionServiceImpl predictionService;
    private ZoneServiceImpl zoneService;

    private JwtTokenProvider jwtTokenProvider;
    private CustomUserDetailsService userDetailsService;

    @BeforeClass
    public void setUp() {
        binRepository = Mockito.mock(BinRepository.class);
        recordRepository = Mockito.mock(FillLevelRecordRepository.class);
        modelRepository = Mockito.mock(UsagePatternModelRepository.class);
        predictionRepository = Mockito.mock(OverflowPredictionRepository.class);
        zoneRepository = Mockito.mock(ZoneRepository.class);

        binService = new BinServiceImpl(binRepository, zoneRepository);
        recordService = new FillLevelRecordServiceImpl(recordRepository, binRepository);
        modelService = new UsagePatternModelServiceImpl(modelRepository, binRepository);
        predictionService = new OverflowPredictionServiceImpl(
                binRepository, recordRepository, modelRepository, predictionRepository, zoneRepository);
        zoneService = new ZoneServiceImpl(zoneRepository);

        jwtTokenProvider = new JwtTokenProvider("VerySecretKeyForJwtDemo1234567890");
        userDetailsService = new CustomUserDetailsService();
    }

    // ------------------------------------------------------------------
    // Small reflection helper to set "id" on JPA entities inside tests
    // ------------------------------------------------------------------
    private void setId(Object entity, Long id) {
        try {
            Field field = entity.getClass().getDeclaredField("id");
            field.setAccessible(true);
            field.set(entity, id);
        } catch (Exception e) {
            throw new RuntimeException("Failed to set id via reflection", e);
        }
    }

    // ---------------------------------------------------------
    // 1. "Develop and deploy a simple servlet using Tomcat Server"
    //    => simulate controller logic via service tests.
    // ---------------------------------------------------------

    @Test(priority = 1, groups = "servlet")
    public void testServlet_likeContextLoadsForBinService() {
        Assert.assertNotNull(binService);
    }

    @Test(priority = 2, groups = "servlet")
    public void testServlet_likeCreateBin() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);
        zone.setZoneName("Downtown");
        zone.setDescription("Central Area");

        Bin bin = new Bin();
        // ID will be generated by DB in real life; not required before save
        bin.setIdentifier("BIN-001");
        bin.setCapacityLiters(100.0);
        bin.setLatitude(10.0);
        bin.setLongitude(20.0);
        bin.setZone(zone);

        when(zoneRepository.findById(1L)).thenReturn(Optional.of(zone));
        when(binRepository.save(any(Bin.class))).thenAnswer(inv -> {
            Bin b = inv.getArgument(0);
            if (b.getId() == null) {
                setId(b, 100L);
            }
            return b;
        });

        Bin created = binService.createBin(bin);

        Assert.assertEquals(created.getIdentifier(), "BIN-001");
        Assert.assertNotNull(created.getZone());
        Assert.assertEquals(created.getZone().getZoneName(), "Downtown");
    }

    @Test(priority = 3, groups = "servlet")
    public void testServlet_likeCreateBinInvalidCapacity() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);
        zone.setZoneName("Downtown");

        Bin bin = new Bin();
        bin.setIdentifier("BIN-002");
        bin.setCapacityLiters(0.0); // invalid
        bin.setLatitude(10.0);
        bin.setLongitude(20.0);
        bin.setZone(zone);

        when(zoneRepository.findById(anyLong())).thenReturn(Optional.of(zone));

        try {
            binService.createBin(bin);
            Assert.fail("Should throw BadRequestException");
        } catch (BadRequestException ex) {
            Assert.assertNotNull(ex.getMessage());
        }
    }

    @Test(priority = 4, groups = "servlet")
    public void testServlet_likeInactiveZoneRejectsBin() {
        Zone zone = new Zone();
        setId(zone, 2L);
        zone.setActive(false);
        zone.setZoneName("Old Zone");

        Bin bin = new Bin();
        bin.setIdentifier("BIN-003");
        bin.setCapacityLiters(100.0);
        bin.setLatitude(10.0);
        bin.setLongitude(20.0);
        bin.setZone(zone);

        when(zoneRepository.findById(2L)).thenReturn(Optional.of(zone));

        try {
            binService.createBin(bin);
            Assert.fail("Expected BadRequestException");
        } catch (BadRequestException ex) {
            Assert.assertNotNull(ex.getMessage());
        }
    }

    @Test(priority = 5, groups = "servlet")
    public void testServlet_like404ForMissingBin() {
        when(binRepository.findById(999L)).thenReturn(Optional.empty());
        try {
            binService.getBinById(999L);
            Assert.fail("Expected ResourceNotFoundException");
        } catch (ResourceNotFoundException ex) {
            Assert.assertTrue(ex.getMessage().contains("Bin not found"));
        }
    }

    @Test(priority = 6, groups = "servlet")
    public void testServlet_likeUpdateBinLocation() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin existing = new Bin();
        setId(existing, 4L);
        existing.setIdentifier("BIN-004");
        existing.setCapacityLiters(100.0);
        existing.setLatitude(10.0);
        existing.setLongitude(20.0);
        existing.setZone(zone);

        when(binRepository.findById(4L)).thenReturn(Optional.of(existing));
        when(zoneRepository.findById(anyLong())).thenReturn(Optional.of(zone));
        when(binRepository.save(any(Bin.class))).thenAnswer(inv -> inv.getArgument(0));

        Bin update = new Bin();
        update.setLocationDescription("Near Park");

        Bin result = binService.updateBin(4L, update);
        Assert.assertEquals(result.getLocationDescription(), "Near Park");
    }

    @Test(priority = 7, groups = "servlet")
    public void testServlet_likeDeactivateBin() {
        Bin bin = new Bin();
        setId(bin, 5L);
        bin.setIdentifier("BIN-005");
        bin.setCapacityLiters(100.0);
        bin.setLatitude(10.0);
        bin.setLongitude(20.0);
        bin.setActive(true);

        when(binRepository.findById(5L)).thenReturn(Optional.of(bin));
        when(binRepository.save(any(Bin.class))).thenAnswer(inv -> inv.getArgument(0));

        binService.deactivateBin(5L);
        Assert.assertFalse(bin.getActive());
    }

    @Test(priority = 8, groups = "servlet")
    public void testServlet_likeGetAllBins() {
        when(binRepository.findAll()).thenReturn(Collections.emptyList());
        Assert.assertNotNull(binService.getAllBins());
    }

    // ---------------------------------------------------------
    // 2. CRUD operations using Spring Boot + REST APIs (service layer)
    // ---------------------------------------------------------

    @Test(priority = 9, groups = "crud")
    public void testCrudCreateZone() {
        Zone zone = new Zone();
        zone.setZoneName("Riverside");
        when(zoneRepository.save(any(Zone.class))).thenAnswer(inv -> {
            Zone z = inv.getArgument(0);
            if (z.getId() == null) {
                setId(z, 10L);
            }
            return z;
        });
        Zone created = zoneService.createZone(zone);
        Assert.assertTrue(created.getActive());
    }

    @Test(priority = 10, groups = "crud")
    public void testCrudGetZoneByIdNotFound() {
        when(zoneRepository.findById(100L)).thenReturn(Optional.empty());
        try {
            zoneService.getZoneById(100L);
            Assert.fail("Expected ResourceNotFoundException");
        } catch (ResourceNotFoundException ex) {
            Assert.assertTrue(ex.getMessage().contains("Zone not found"));
        }
    }

    @Test(priority = 11, groups = "crud")
    public void testCrudUpdateZoneDescription() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setZoneName("Central");
        when(zoneRepository.findById(1L)).thenReturn(Optional.of(zone));
        when(zoneRepository.save(any(Zone.class))).thenAnswer(inv -> inv.getArgument(0));

        Zone update = new Zone();
        update.setDescription("Central business district");
        Zone result = zoneService.updateZone(1L, update);
        Assert.assertEquals(result.getDescription(), "Central business district");
    }

    @Test(priority = 12, groups = "crud")
    public void testCrudDeactivateZone() {
        Zone zone = new Zone();
        setId(zone, 2L);
        zone.setZoneName("West");
        zone.setActive(true);
        when(zoneRepository.findById(2L)).thenReturn(Optional.of(zone));
        when(zoneRepository.save(any(Zone.class))).thenAnswer(inv -> inv.getArgument(0));

        zoneService.deactivateZone(2L);
        Assert.assertFalse(zone.getActive());
    }

    @Test(priority = 13, groups = "crud")
    public void testCrudCreateFillRecord() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 10L);
        bin.setZone(zone);
        bin.setCapacityLiters(100.0);
        bin.setIdentifier("BIN-010");
        bin.setActive(true);

        FillLevelRecord record = new FillLevelRecord();
        record.setBin(bin);
        record.setFillPercentage(50.0);
        record.setRecordedAt(LocalDateTime.now().minusHours(1));

        when(binRepository.findById(10L)).thenReturn(Optional.of(bin));
        when(recordRepository.save(any(FillLevelRecord.class))).thenAnswer(inv -> {
            FillLevelRecord r = inv.getArgument(0);
            if (r.getId() == null) {
                setId(r, 200L);
            }
            return r;
        });

        FillLevelRecord created = recordService.createRecord(record);
        Assert.assertEquals(created.getFillPercentage(), 50.0);
    }

    @Test(priority = 14, groups = "crud")
    public void testCrudRejectFutureRecordedAt() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 11L);
        bin.setZone(zone);
        bin.setActive(true);

        FillLevelRecord record = new FillLevelRecord();
        record.setBin(bin);
        record.setFillPercentage(60.0);
        record.setRecordedAt(LocalDateTime.now().plusHours(2)); // future

        when(binRepository.findById(11L)).thenReturn(Optional.of(bin));

        try {
            recordService.createRecord(record);
            Assert.fail("Expected BadRequestException");
        } catch (BadRequestException ex) {
            Assert.assertNotNull(ex.getMessage());
        }
    }

    @Test(priority = 15, groups = "crud")
    public void testCrudGetRecordById() {
        FillLevelRecord record = new FillLevelRecord();
        record.setFillPercentage(70.0);
        when(recordRepository.findById(1L)).thenReturn(Optional.of(record));
        FillLevelRecord found = recordService.getRecordById(1L);
        Assert.assertEquals(found.getFillPercentage(), 70.0);
    }

    @Test(priority = 16, groups = "crud")
    public void testCrudGetRecentRecordsWithLimit() {
        Bin bin = new Bin();
        setId(bin, 3L);
        when(binRepository.findById(3L)).thenReturn(Optional.of(bin));

        List<FillLevelRecord> list = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            FillLevelRecord r = new FillLevelRecord();
            r.setFillPercentage(10.0 * i);
            list.add(r);
        }
        when(recordRepository.findByBinOrderByRecordedAtDesc(bin)).thenReturn(list);

        List<FillLevelRecord> recent = recordService.getRecentRecords(3L, 3);
        Assert.assertEquals(recent.size(), 3);
    }

    // ---------------------------------------------------------
    // 3. DI and IoC configuration tests
    // ---------------------------------------------------------

    @Test(priority = 17, groups = "di")
    public void testDI_BinServiceUsesZoneRepository() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);
        zone.setZoneName("Downtown");

        Bin bin = new Bin();
        bin.setIdentifier("BIN-020");
        bin.setCapacityLiters(100.0);
        bin.setLatitude(1.0);
        bin.setLongitude(2.0);
        bin.setZone(zone);

        when(zoneRepository.findById(1L)).thenReturn(Optional.of(zone));
        when(binRepository.save(any(Bin.class))).thenAnswer(inv -> inv.getArgument(0));

        Bin created = binService.createBin(bin);
        Assert.assertNotNull(created.getZone());
        Assert.assertEquals(created.getZone().getZoneName(), "Downtown");
    }

    @Test(priority = 18, groups = "di")
    public void testDI_UsageModelServiceUsesBinRepository() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 30L);
        bin.setZone(zone);
        bin.setIdentifier("BIN-030");
        bin.setCapacityLiters(100.0);
        bin.setActive(true);

        UsagePatternModel model = new UsagePatternModel();
        model.setBin(bin);
        model.setAvgDailyIncreaseWeekday(10.0);
        model.setAvgDailyIncreaseWeekend(5.0);

        when(binRepository.findById(30L)).thenReturn(Optional.of(bin));
        when(modelRepository.save(any(UsagePatternModel.class))).thenAnswer(inv -> inv.getArgument(0));

        UsagePatternModel saved = modelService.createModel(model);
        Assert.assertEquals(saved.getAvgDailyIncreaseWeekday(), 10.0);
    }

    @Test(priority = 19, groups = "di")
    public void testDI_ZoneServiceInjectedCorrectly() {
        Assert.assertNotNull(zoneService);
    }

    @Test(priority = 20, groups = "di")
    public void testDI_PredictionServiceInjectedDependencies() {
        Assert.assertNotNull(predictionService);
    }

    @Test(priority = 21, groups = "di")
    public void testDI_ModelServiceRejectsNegativeIncrease() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 31L);
        bin.setZone(zone);
        bin.setIdentifier("BIN-031");
        bin.setActive(true);

        UsagePatternModel model = new UsagePatternModel();
        model.setBin(bin);
        model.setAvgDailyIncreaseWeekday(-1.0); // invalid
        model.setAvgDailyIncreaseWeekend(5.0);

        when(binRepository.findById(31L)).thenReturn(Optional.of(bin));

        try {
            modelService.createModel(model);
            Assert.fail("Expected BadRequestException");
        } catch (BadRequestException ex) {
            Assert.assertNotNull(ex.getMessage());
        }
    }

    @Test(priority = 22, groups = "di")
    public void testDI_InjectRepositoriesForRecordService() {
        Assert.assertNotNull(recordService);
    }

    @Test(priority = 23, groups = "di")
    public void testDI_MultipleBeansNotNull() {
        Assert.assertNotNull(binRepository);
        Assert.assertNotNull(recordRepository);
        Assert.assertNotNull(modelRepository);
    }

    @Test(priority = 24, groups = "di")
    public void testDI_CustomUserDetailsServiceAvailable() {
        Assert.assertNotNull(userDetailsService);
    }

    // ---------------------------------------------------------
    // 4. Hibernate configurations, generator, annotations, CRUD
    // ---------------------------------------------------------

    @Test(priority = 25, groups = "hibernate")
    public void testHibernate_BinHasGeneratedId() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        bin.setIdentifier("BIN-040");
        bin.setCapacityLiters(100.0);
        bin.setLatitude(1.0);
        bin.setLongitude(2.0);
        bin.setZone(zone);

        when(zoneRepository.findById(1L)).thenReturn(Optional.of(zone));
        when(binRepository.save(any(Bin.class))).thenAnswer(inv -> {
            Bin b = inv.getArgument(0);
            if (b.getId() == null) {
                setId(b, 40L); // simulate DB-generated ID
            }
            return b;
        });

        Bin saved = binService.createBin(bin);
        Assert.assertNotNull(saved.getId());
        Assert.assertEquals(saved.getIdentifier(), "BIN-040");
    }

    @Test(priority = 26, groups = "hibernate")
    public void testHibernate_FillRecordAnnotations() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 50L);
        bin.setZone(zone);
        bin.setActive(true);

        FillLevelRecord record = new FillLevelRecord();
        record.setFillPercentage(80.0);
        record.setRecordedAt(LocalDateTime.now());
        record.setBin(bin);

        when(binRepository.findById(50L)).thenReturn(Optional.of(bin));
        when(recordRepository.save(any(FillLevelRecord.class))).thenAnswer(inv -> inv.getArgument(0));

        FillLevelRecord saved = recordService.createRecord(record);
        Assert.assertEquals(saved.getFillPercentage(), 80.0);
        Assert.assertNotNull(saved.getRecordedAt());
    }

    @Test(priority = 27, groups = "hibernate")
    public void testHibernate_UsageModelCRUDFullCycle() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 60L);
        bin.setZone(zone);
        bin.setIdentifier("BIN-050");
        bin.setCapacityLiters(100.0);
        bin.setActive(true);

        when(binRepository.findById(60L)).thenReturn(Optional.of(bin));
        when(modelRepository.save(any(UsagePatternModel.class))).thenAnswer(inv -> inv.getArgument(0));

        UsagePatternModel model = new UsagePatternModel();
        model.setBin(bin);
        model.setAvgDailyIncreaseWeekday(12.0);
        model.setAvgDailyIncreaseWeekend(6.0);

        UsagePatternModel saved = modelService.createModel(model);
        Assert.assertEquals(saved.getAvgDailyIncreaseWeekend(), 6.0);

        UsagePatternModel update = new UsagePatternModel();
        update.setAvgDailyIncreaseWeekend(7.0);

        when(modelRepository.findById(1L)).thenReturn(Optional.of(saved));
        UsagePatternModel updated = modelService.updateModel(1L, update);

        Assert.assertEquals(updated.getAvgDailyIncreaseWeekend(), 7.0);
    }

    @Test(priority = 28, groups = "hibernate")
    public void testHibernate_OverflowPredictionEntity() {
        Bin bin = new Bin();
        OverflowPrediction prediction = new OverflowPrediction();
        prediction.setBin(bin);
        prediction.setDaysUntilFull(3);
        prediction.setPredictedFullDate(LocalDate.now().plusDays(3));

        when(predictionRepository.save(any(OverflowPrediction.class))).thenAnswer(inv -> inv.getArgument(0));
        OverflowPrediction saved = predictionRepository.save(prediction);
        Assert.assertEquals(saved.getDaysUntilFull().intValue(), 3);
    }

    @Test(priority = 29, groups = "hibernate")
    public void testHibernate_ZoneUniqueNameRuleConcept() {
        Zone zone = new Zone();
        zone.setZoneName("UniqueZone");
        when(zoneRepository.save(any(Zone.class))).thenAnswer(inv -> inv.getArgument(0));
        Zone saved = zoneService.createZone(zone);
        Assert.assertEquals(saved.getZoneName(), "UniqueZone");
    }

    @Test(priority = 30, groups = "hibernate")
    public void testHibernate_BinActiveDefaultsTrue() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        bin.setIdentifier("BIN-060");
        bin.setCapacityLiters(100.0);
        bin.setLatitude(1.0);
        bin.setLongitude(2.0);
        bin.setZone(zone); // active zone

        when(zoneRepository.findById(1L)).thenReturn(Optional.of(zone));
        when(binRepository.save(any(Bin.class))).thenAnswer(inv -> {
            Bin b = inv.getArgument(0);
            if (b.getActive() == null) {
                b.setActive(true);
            }
            return b;
        });

        Bin saved = binService.createBin(bin);
        Assert.assertTrue(saved.getActive());
    }

    @Test(priority = 31, groups = "hibernate")
    public void testHibernate_FillPercentageBoundsPositiveCase() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 70L);
        bin.setZone(zone);
        bin.setActive(true);

        FillLevelRecord record = new FillLevelRecord();
        record.setFillPercentage(0.0);
        record.setRecordedAt(LocalDateTime.now());
        record.setBin(bin);

        when(binRepository.findById(70L)).thenReturn(Optional.of(bin));
        when(recordRepository.save(any(FillLevelRecord.class))).thenAnswer(inv -> inv.getArgument(0));

        FillLevelRecord saved = recordService.createRecord(record);
        Assert.assertEquals(saved.getFillPercentage(), 0.0);
    }

    @Test(priority = 32, groups = "hibernate")
    public void testHibernate_RejectInactiveBinForFillRecord() {
        Zone zone = new Zone();
        setId(zone, 1L);
        zone.setActive(true);

        Bin bin = new Bin();
        setId(bin, 80L);
        bin.setZone(zone);
        bin.setActive(false); // inactive bin

        FillLevelRecord record = new FillLevelRecord();
        record.setBin(bin);
        record.setFillPercentage(50.0);
        record.setRecordedAt(LocalDateTime.now());

        when(binRepository.findById(80L)).thenReturn(Optional.of(bin));

        try {
            recordService.createRecord(record);
            Assert.fail("Expected BadRequestException");
        } catch (BadRequestException ex) {
            Assert.assertNotNull(ex.getMessage());
        }
    }

    // ---------------------------------------------------------
    // 5. JPA mapping & normalization (1NF, 2NF, 3NF) style tests
    // ---------------------------------------------------------

    @Test(priority = 33, groups = "jpa")
    public void testJPA_BinZoneMapping() {
        Zone zone = new Zone();
        zone.setZoneName("Central");
        Bin bin = new Bin();
        bin.setIdentifier("BIN-070");
        bin.setZone(zone);
        Assert.assertEquals(bin.getZone().getZoneName(), "Central");
    }

    @Test(priority = 34, groups = "jpa")
    public void testJPA_FillRecordBinMapping() {
        Bin bin = new Bin();
        bin.setIdentifier("BIN-071");
        FillLevelRecord record = new FillLevelRecord();
        record.setBin(bin);
        Assert.assertEquals(record.getBin().getIdentifier(), "BIN-071");
    }

    @Test(priority = 35, groups = "jpa")
    public void testJPA_UsageModelBinMapping() {
        Bin bin = new Bin();
        bin.setIdentifier("BIN-072");
        UsagePatternModel model = new UsagePatternModel();
        model.setBin(bin);
        Assert.assertEquals(model.getBin().getIdentifier(), "BIN-072");
    }

    @Test(priority = 36, groups = "jpa")
    public void testJPA_OverflowPredictionBinMapping() {
        Bin bin = new Bin();
        bin.setIdentifier("BIN-073");
        OverflowPrediction prediction = new OverflowPrediction();
        prediction.setBin(bin);
        Assert.assertEquals(prediction.getBin().getIdentifier(), "BIN-073");
    }

    @Test(priority = 37, groups = "jpa")
    public void testJPA_NormalizationNoDuplicateZoneFieldsInBin() {
        Zone zone = new Zone();
        zone.setZoneName("NormalizedZone");
        Bin bin = new Bin();
        bin.setZone(zone);
        Assert.assertEquals(bin.getZone().getZoneName(), "NormalizedZone");
    }

    @Test(priority = 38, groups = "jpa")
    public void testJPA_OneBinMultipleRecords() {
        Bin bin = new Bin();
        bin.setIdentifier("BIN-074");
        FillLevelRecord r1 = new FillLevelRecord();
        r1.setBin(bin);
        FillLevelRecord r2 = new FillLevelRecord();
        r2.setBin(bin);
        Assert.assertEquals(r1.getBin(), r2.getBin());
    }

    @Test(priority = 39, groups = "jpa")
    public void testJPA_ZoneActiveConstraint() {
        Zone zone = new Zone();
        zone.setActive(true);
        Assert.assertTrue(zone.getActive());
    }

    @Test(priority = 40, groups = "jpa")
    public void testJPA_NoTransitiveDependencyViolation() {
        Zone zone = new Zone();
        zone.setZoneName("Z1");
        zone.setDescription("Description");
        Bin bin = new Bin();
        bin.setZone(zone);
        Assert.assertEquals(bin.getZone().getDescription(), "Description");
    }

    // ---------------------------------------------------------
    // 6. Many-to-Many relationships & associations (simulate bin-zone relations)
    // ---------------------------------------------------------

    @Test(priority = 41, groups = "associations")
    public void testAssociations_MultipleBinsSameZone() {
        Zone zone = new Zone();
        zone.setZoneName("SharedZone");
        Bin b1 = new Bin();
        b1.setZone(zone);
        Bin b2 = new Bin();
        b2.setZone(zone);
        Assert.assertEquals(b1.getZone(), b2.getZone());
    }

    @Test(priority = 42, groups = "associations")
    public void testAssociations_ModelPerBinLatestOnlyLogical() {
        Bin bin = new Bin();
        setId(bin, 1L);
        bin.setIdentifier("BIN-080");
        UsagePatternModel m1 = new UsagePatternModel();
        m1.setBin(bin);
        UsagePatternModel m2 = new UsagePatternModel();
        m2.setBin(bin);
        List<UsagePatternModel> list = Arrays.asList(m1, m2);

        when(binRepository.findById(1L)).thenReturn(Optional.of(bin));
        when(modelRepository.findTop1ByBinOrderByLastUpdatedDesc(bin)).thenReturn(Optional.of(m2));

        UsagePatternModel latest = modelService.getModelForBin(1L);
        Assert.assertEquals(latest, m2);
        Assert.assertEquals(list.get(1), latest);
    }

    @Test(priority = 43, groups = "associations")
    public void testAssociations_PredictionUsesModelAndBin() {
        Bin bin = new Bin();
        setId(bin, 1L);
        bin.setIdentifier("BIN-081");
        bin.setCapacityLiters(100.0);

        FillLevelRecord record = new FillLevelRecord();
        record.setBin(bin);
        record.setFillPercentage(50.0);
        record.setRecordedAt(LocalDateTime.now());

        UsagePatternModel model = new UsagePatternModel();
        model.setBin(bin);
        model.setAvgDailyIncreaseWeekday(10.0);
        model.setAvgDailyIncreaseWeekend(5.0);

        when(binRepository.findById(1L)).thenReturn(Optional.of(bin));
        when(recordRepository.findTop1ByBinOrderByRecordedAtDesc(bin)).thenReturn(Optional.of(record));
        when(modelRepository.findTop1ByBinOrderByLastUpdatedDesc(bin)).thenReturn(Optional.of(model));
        when(predictionRepository.save(any(OverflowPrediction.class))).thenAnswer(inv -> inv.getArgument(0));

        OverflowPrediction prediction = predictionService.generatePrediction(1L);
        Assert.assertEquals(prediction.getBin(), bin);
        Assert.assertEquals(prediction.getModelUsed(), model);
    }

    @Test(priority = 44, groups = "associations")
    public void testAssociations_ZoneWithMultiplePredictions() {
        Zone zone = new Zone();
        Bin b1 = new Bin();
        b1.setZone(zone);
        OverflowPrediction p1 = new OverflowPrediction();
        p1.setBin(b1);
        OverflowPrediction p2 = new OverflowPrediction();
        p2.setBin(b1);
        List<OverflowPrediction> list = Arrays.asList(p1, p2);
        Assert.assertEquals(list.get(0).getBin().getZone(), list.get(1).getBin().getZone());
    }

    @Test(priority = 45, groups = "associations")
    public void testAssociations_LogicalManyBinsPerZone() {
        Zone zone = new Zone();
        zone.setZoneName("ManyBinsZone");
        Bin b1 = new Bin();
        Bin b2 = new Bin();
        b1.setZone(zone);
        b2.setZone(zone);
        Assert.assertEquals(b1.getZone().getZoneName(), b2.getZone().getZoneName());
    }

    @Test(priority = 46, groups = "associations")
    public void testAssociations_FillRecordsPerBinConceptualManyToOne() {
        Bin bin = new Bin();
        FillLevelRecord r1 = new FillLevelRecord();
        FillLevelRecord r2 = new FillLevelRecord();
        r1.setBin(bin);
        r2.setBin(bin);
        Assert.assertSame(r1.getBin(), r2.getBin());
    }

    @Test(priority = 47, groups = "associations")
    public void testAssociations_ModelReuseAcrossBinsInvalidScenario() {
        Bin b1 = new Bin();
        Bin b2 = new Bin();
        UsagePatternModel model = new UsagePatternModel();
        model.setBin(b1);
        Assert.assertNotEquals(b2, model.getBin());
    }

    @Test(priority = 48, groups = "associations")
    public void testAssociations_ZoneDeactivationAffectsBinsConceptually() {
        Zone zone = new Zone();
        zone.setActive(false);
        Bin bin = new Bin();
        bin.setZone(zone);
        Assert.assertFalse(bin.getZone().getActive());
    }

    // ---------------------------------------------------------
    // 7. Security controls & JWT authentication
    // ---------------------------------------------------------

    @Test(priority = 49, groups = "security")
    public void testSecurity_GenerateJwtToken() {
        UsernamePasswordAuthenticationToken auth =
                new UsernamePasswordAuthenticationToken("admin@city.com", "admin123", Collections.emptyList());
        String token = jwtTokenProvider.generateToken(auth, 1L, "ADMIN", "admin@city.com");
        Assert.assertNotNull(token);
    }

    @Test(priority = 50, groups = "security")
    public void testSecurity_JwtContainsEmailAndRole() {
        UsernamePasswordAuthenticationToken auth =
                new UsernamePasswordAuthenticationToken("user@city.com", "user123", Collections.emptyList());
        String token = jwtTokenProvider.generateToken(auth, 2L, "USER", "user@city.com");
        Assert.assertTrue(token.length() > 10);
    }

    @Test(priority = 51, groups = "security")
    public void testSecurity_UserDetailsServiceDefaultAdmin() {
        CustomUserDetailsService.DemoUser user = userDetailsService.getByEmail("admin@city.com");
        Assert.assertEquals(user.getRole(), "ADMIN");
    }

    @Test(priority = 52, groups = "security")
    public void testSecurity_RegisterNewUser() {
        CustomUserDetailsService.DemoUser user =
                userDetailsService.registerUser("Test User", "test@city.com", "password");
        Assert.assertEquals(user.getEmail(), "test@city.com");
    }

    @Test(priority = 53, groups = "security")
    public void testSecurity_RegisterDuplicateUserFails() {
        userDetailsService.registerUser("User1", "dup@city.com", "pwd");
        try {
            userDetailsService.registerUser("User2", "dup@city.com", "pwd2");
            Assert.fail("Expected exception for duplicate");
        } catch (RuntimeException ex) {
            Assert.assertTrue(ex.getMessage().contains("exists"));
        }
    }

    @Test(priority = 54, groups = "security")
    public void testSecurity_LoadUserDetailsSuccess() {
        userDetailsService.registerUser("User3", "user3@city.com", "pwd");
        Assert.assertNotNull(userDetailsService.loadUserByUsername("user3@city.com"));
    }

    @Test(priority = 55, groups = "security")
    public void testSecurity_LoadUserDetailsNotFound() {
        try {
            userDetailsService.loadUserByUsername("no_such_user@city.com");
            Assert.fail("Expected UsernameNotFoundException");
        } catch (Exception ex) {
            Assert.assertTrue(ex.getMessage().contains("User not found"));
        }
    }

    @Test(priority = 56, groups = "security")
    public void testSecurity_JwtExpirationConfig() {
        UsernamePasswordAuthenticationToken auth =
                new UsernamePasswordAuthenticationToken("admin@city.com", "admin123", Collections.emptyList());
        String token = jwtTokenProvider.generateToken(auth, 1L, "ADMIN", "admin@city.com");
        Assert.assertNotNull(token);
    }

    // ---------------------------------------------------------
    // 8. HQL / HCQL-like advanced querying via Spring Data
    // ---------------------------------------------------------

    @Test(priority = 57, groups = "hql")
    public void testHQL_FindLatestPredictionForZone() {
        Zone zone = new Zone();
        setId(zone, 1L);
        Bin bin = new Bin();
        bin.setZone(zone);

        OverflowPrediction p1 = new OverflowPrediction();
        p1.setBin(bin);
        p1.setDaysUntilFull(2);
        OverflowPrediction p2 = new OverflowPrediction();
        p2.setBin(bin);
        p2.setDaysUntilFull(5);

        List<OverflowPrediction> latest = Arrays.asList(p1, p2);
        when(zoneRepository.findById(1L)).thenReturn(Optional.of(zone));
        when(predictionRepository.findLatestPredictionsForZone(zone)).thenReturn(latest);

        List<OverflowPrediction> result = predictionService.getLatestPredictionsForZone(1L);
        Assert.assertEquals(result.size(), 2);
    }

    @Test(priority = 58, groups = "hql")
    public void testHQL_FindByBinOrderByRecordedAtDesc() {
        Bin bin = new Bin();
        FillLevelRecord r1 = new FillLevelRecord();
        FillLevelRecord r2 = new FillLevelRecord();
        List<FillLevelRecord> records = Arrays.asList(r1, r2);
        when(recordRepository.findByBinOrderByRecordedAtDesc(bin)).thenReturn(records);
        List<FillLevelRecord> found = recordRepository.findByBinOrderByRecordedAtDesc(bin);
        Assert.assertEquals(found.size(), 2);
    }

    @Test(priority = 59, groups = "hql")
    public void testHQL_FindTop1ByBinOrderByRecordedAtDesc() {
        Bin bin = new Bin();
        FillLevelRecord record = new FillLevelRecord();
        when(recordRepository.findTop1ByBinOrderByRecordedAtDesc(bin)).thenReturn(Optional.of(record));
        Optional<FillLevelRecord> latest = recordRepository.findTop1ByBinOrderByRecordedAtDesc(bin);
        Assert.assertTrue(latest.isPresent());
    }

    @Test(priority = 60, groups = "hql")
    public void testHQL_FindTop1ModelByBinOrderByLastUpdatedDesc() {
        Bin bin = new Bin();
        UsagePatternModel model = new UsagePatternModel();
        when(modelRepository.findTop1ByBinOrderByLastUpdatedDesc(bin)).thenReturn(Optional.of(model));
        Optional<UsagePatternModel> latest = modelRepository.findTop1ByBinOrderByLastUpdatedDesc(bin);
        Assert.assertTrue(latest.isPresent());
    }

    @Test(priority = 61, groups = "hql")
    public void testHQL_FindBinsByZoneAndActiveTrue() {
        Zone zone = new Zone();
        Bin b1 = new Bin();
        Bin b2 = new Bin();
        when(binRepository.findByZoneAndActiveTrue(zone)).thenReturn(Arrays.asList(b1, b2));
        List<Bin> bins = binRepository.findByZoneAndActiveTrue(zone);
        Assert.assertEquals(bins.size(), 2);
    }

    @Test(priority = 62, groups = "hql")
    public void testHQL_FindZoneByZoneName() {
        Zone zone = new Zone();
        zone.setZoneName("Downtown");
        when(zoneRepository.findByZoneName("Downtown")).thenReturn(Optional.of(zone));
        Optional<Zone> found = zoneRepository.findByZoneName("Downtown");
        Assert.assertTrue(found.isPresent());
    }

    @Test(priority = 63, groups = "hql")
    public void testHQL_FindRecordsWithinTimeRange() {
        Bin bin = new Bin();
        LocalDateTime start = LocalDateTime.now().minusDays(1);
        LocalDateTime end = LocalDateTime.now();
        List<FillLevelRecord> list = Collections.singletonList(new FillLevelRecord());
        when(recordRepository.findByBinAndRecordedAtBetween(bin, start, end)).thenReturn(list);
        List<FillLevelRecord> result = recordRepository.findByBinAndRecordedAtBetween(bin, start, end);
        Assert.assertEquals(result.size(), 1);
    }

    @Test(priority = 64, groups = "hql")
    public void testHQL_FindByIdentifierForBin() {
        Bin bin = new Bin();
        bin.setIdentifier("BIN-HQL-1");
        when(binRepository.findByIdentifier("BIN-HQL-1")).thenReturn(Optional.of(bin));
        Optional<Bin> found = binRepository.findByIdentifier("BIN-HQL-1");
        Assert.assertTrue(found.isPresent());
        Assert.assertEquals(found.get().getIdentifier(), "BIN-HQL-1");
    }
}
